### ISSUE TITLE
Upgrade EF version?

### ISSUE THREAD

**Issue by fagnercarvalho** [khellang/EF.Interception#1]
I was trying to use this library along with EF 6.1.3 but this is using EF5. Can we upgrade this library to the last version of EF or we got something similar in EF6 onwards?

**Comment by khellang** [comment]
Hello Fagner!

Unfortunately I don't use this library much anymore and I won't have much time to spend on it.

I would :heart: to take a PR for this if you're up to the taks?

AFAIK there's no built-in feature for this in EF6 still...

**Comment by khellang** [comment]
I've pushed v0.2 with the recent changes. I also upgraded to EF 6.1.3. It would be super cool if you could test it out and let me know how it works :smile:

**Comment by fagnercarvalho** [comment]
Hello Kristian.

I used the new version and it seems to be running smoothly. I really appreciate your time on this!

Thank you for everything. :smiley:

**Comment by khellang** [comment]
No problem! Glad someone else found this project useful :grin:
