### ISSUE TITLE
Can't run any Post method (PostInsert, PostUpdate and PostDelete)

### ISSUE THREAD

**Issue by fagnercarvalho** [khellang/EF.Interception#2]
Somehow I can't run any of my Post methods (`PostInsert`, `PostUpdate`, `PostDelete`) because after calling `base.SaveChanges()` from inside the `SaveChanges()` in `InterceptionDbContext` class the modifiedEntries items receive the state 'Unchanged'. Because of that the `Intercept` in `Interceptor` class can't find any method (that are supposed to be `PostInsert`, `PostUpdate` or `PostDelete`) that is compatible with the 'Unchanged' state because they got 'Added', 'Updated' and 'Deleted' states, respectively.

**Comment by khellang** [comment]
Closed with #3
